name: Check Frontend_React_Task2 File Structure

# Triggers the action only on a direct commit push (no pull request)
on:
  push:
    branches:
      - '**'  # Runs the action on commit pushed to any branch

jobs:
  check-task2-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check required files
        run: |
          REQUIRED_FILES=("profile-website/src/components/HoverInfo.jsx" "profile-website/src/components/ProfileItem.jsx" "profile-website/src/components/ProfileList.jsx" "profile-website/src/components/SearchBar.jsx" "profile-website/src/components/WelcomeBanner.jsx" "profile-website/src/components/withLogger.jsx" "profile-website/src/App.js" "profile-website/src/App.css")
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "$file is missing!"
              exit 1
            fi
          done
